#!/usr/bin/env node
// Generates the distributable APT design artifacts from the canonical tokens (APT-019).
//
//   design/tokens/APT-TOKENS.json  ->  design/generated/apt-tokens.css            (:root light, .dark dark)
//                                      design/generated/apt-tokens.dark-first.css (:root dark, .light light)
//                                      design/generated/tailwind-preset.cjs       (Tailwind v3 preset)
//                                      design/generated/apt-theme.css             (Tailwind v4 @theme inline)
//                                      design/generated/tokens.ts                 (typed values)
//                                      design/generated/apt-preview.html          (portable token preview)
//                                      references/design-tokens.json         (color values only)
//
// Usage: node scripts/build-design.mjs [--check]
// --check writes nothing and exits 1 when any generated file is stale.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const tokensPath = path.join(root, "design", "tokens", "APT-TOKENS.json");
const version = readFileSync(path.join(root, "design", "VERSION"), "utf8").trim();
const tokens = JSON.parse(readFileSync(tokensPath, "utf8")).apt;

const HEADER = (what) =>
  `APT design tokens v${version} - ${what}.\n` +
  "GENERATED by apt-principles-agents/scripts/build-design.mjs from design/tokens/APT-TOKENS.json.\n" +
  "Do not edit: change the canonical tokens and re-run the generator, then sync with apt-assets.";

/** "hsl(220, 70%, 61%)" or "hsl(220, 20%, 4% / 0.82)" -> "220 70% 61%" / "220 20% 4% / 0.82" */
function channels(value) {
  const match = /^hsl\((.*)\)$/.exec(String(value).trim());
  if (!match) throw new Error(`Expected hsl() value, got ${value}`);
  return match[1].replace(/,/g, " ").replace(/\s+/g, " ").trim();
}

/** Ordered CSS custom properties for one theme. */
function themeVariables(theme) {
  const vars = [];
  for (const [name, token] of Object.entries(tokens.color[theme])) vars.push([name, channels(token.value)]);
  const charts = tokens.color[theme === "dark" ? "chart" : "chartLight"];
  for (const [index, token] of Object.entries(charts)) vars.push([`chart-${index}`, channels(token.value)]);
  for (let level = 1; level <= 4; level++) vars.push([`elevation-${level}`, tokens.shadow[`elevation-${level}-${theme}`].value]);
  vars.push(["elevation-glow-subtle", tokens.shadow["apt-glow-subtle"].value]);
  vars.push(["elevation-glow-strong", tokens.shadow["apt-glow-strong"].value]);
  vars.push(["elevation-hover-lift", tokens.shadow["apt-hover-lift"].value]);
  return vars;
}

function sharedVariables() {
  const duration = tokens.animation.duration;
  return [
    ["radius", tokens.borderRadius.lg.value],
    ["motion-fast", duration.fast.value],
    ["motion-medium", duration.normal.value],
    ["motion-slow", duration.slow.value],
  ];
}

const block = (selector, vars) => `${selector} {\n${vars.map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}`;

function tokensCss(layout) {
  const [rootTheme, classSelector, classTheme] = layout === "light-first" ? ["light", ".dark", "dark"] : ["dark", ".light", "light"];
  return [
    `/*\n${HEADER(`${layout} theme layout (:root ${rootTheme}, ${classSelector} ${classTheme})`)}\n*/`,
    block(":root", [...sharedVariables(), ...themeVariables(rootTheme)]),
    block(classSelector, themeVariables(classTheme)),
    "",
  ].join("\n\n");
}

/** Tailwind color map: semantic token -> hsl(var(--token)), grouping "<name>-foreground" pairs. */
function tailwindColors() {
  const names = Object.keys(tokens.color.dark);
  const colors = {};
  for (const name of names) {
    if (name.endsWith("-foreground") && names.includes(name.replace(/-foreground$/, ""))) continue;
    if (name.startsWith("sidebar-")) continue;
    const foreground = `${name}-foreground`;
    colors[name] = names.includes(foreground)
      ? { DEFAULT: `hsl(var(--${name}))`, foreground: `hsl(var(--${foreground}))` }
      : `hsl(var(--${name}))`;
  }
  colors.sidebar = { DEFAULT: "hsl(var(--sidebar-background))" };
  for (const name of names.filter((n) => n.startsWith("sidebar-") && n !== "sidebar-background")) {
    colors.sidebar[name.replace("sidebar-", "")] = `hsl(var(--${name}))`;
  }
  colors.chart = Object.fromEntries(Object.keys(tokens.color.chart).map((i) => [i, `hsl(var(--chart-${i}))`]));
  return colors;
}

function tailwindPreset() {
  const container = tokens.container.maxWidth;
  const preset = {
    darkMode: ["class"],
    theme: {
      extend: {
        colors: tailwindColors(),
        borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
        boxShadow: {
          "elevation-1": "var(--elevation-1)",
          "elevation-2": "var(--elevation-2)",
          "elevation-3": "var(--elevation-3)",
          "elevation-4": "var(--elevation-4)",
          "apt-glow-subtle": "var(--elevation-glow-subtle)",
          "apt-glow-strong": "var(--elevation-glow-strong)",
          "apt-hover-lift": "var(--elevation-hover-lift)",
        },
        transitionDuration: { fast: "var(--motion-fast)", medium: "var(--motion-medium)", slow: "var(--motion-slow)" },
        maxWidth: Object.fromEntries(Object.entries(container).map(([k, v]) => [k, v.value])),
      },
    },
  };
  return `/*\n${HEADER("Tailwind CSS v3 preset")}\nUsage: presets: [require("./.apt/design/generated/tailwind-preset.cjs")]\n*/\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
}

function tailwindV4Theme() {
  const lines = [];
  const flatten = (prefix, value) => {
    if (typeof value === "string") lines.push(`  --color-${prefix}: ${value};`);
    else for (const [k, v] of Object.entries(value)) flatten(k === "DEFAULT" ? prefix : `${prefix}-${k}`, v);
  };
  for (const [name, value] of Object.entries(tailwindColors())) flatten(name, value);
  for (let level = 1; level <= 4; level++) lines.push(`  --shadow-elevation-${level}: var(--elevation-${level});`);
  lines.push("  --radius-lg: var(--radius);", "  --radius-md: calc(var(--radius) - 2px);", "  --radius-sm: calc(var(--radius) - 4px);");
  return `/*\n${HEADER("Tailwind CSS v4 theme mapping")}\nImport after apt-tokens*.css: @import "./.apt/design/generated/apt-theme.css";\n*/\n@theme inline {\n${lines.join("\n")}\n}\n`;
}

function previewHtml() {
  const css = tokensCss("dark-first");
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>APT design preview v${version}</title>
<style>
${css}
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 2rem;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
  background: hsl(var(--background));
  color: hsl(var(--foreground));
  line-height: 1.5;
}
main { max-width: 52rem; }
h1 { font-size: 1.75rem; line-height: 1.15; margin: 0 0 0.5rem; }
h2 { font-size: 1.1rem; margin: 2rem 0 0.75rem; }
p { color: hsl(var(--muted-foreground)); margin: 0 0 1rem; }
.row { display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: center; }
.swatch {
  width: 7.5rem;
  border: 1px solid hsl(var(--border));
  border-radius: var(--radius);
  overflow: hidden;
  background: hsl(var(--card));
}
.swatch i { display: block; height: 3rem; }
.swatch span { display: block; padding: 0.4rem 0.5rem; font-size: 0.75rem; }
button, .option {
  font: inherit;
  border-radius: var(--radius);
  border: 1px solid transparent;
  padding: 0.5rem 1rem;
  cursor: pointer;
  transition: background var(--motion-fast) ease-out, color var(--motion-fast) ease-out, box-shadow var(--motion-fast) ease-out;
}
button:focus-visible, .option:focus-visible {
  outline: 2px solid hsl(var(--ring));
  outline-offset: 2px;
}
.primary { background: hsl(var(--primary)); color: hsl(var(--primary-foreground)); }
.primary:hover { filter: brightness(1.08); }
.outline, .ghost, .option { background: transparent; color: hsl(var(--foreground)); }
.outline { border-color: hsl(var(--border)); }
.outline:hover, .ghost:hover, .option:hover, .option:focus {
  background: hsl(var(--accent));
  color: hsl(var(--accent-foreground));
}
.menu {
  width: 16rem;
  padding: 0.35rem;
  border: 1px solid hsl(var(--border));
  border-radius: var(--radius);
  background: hsl(var(--popover));
}
.option { display: block; width: 100%; text-align: left; }
.bar { height: 0.5rem; width: 2rem; border-radius: 999px; background: hsl(var(--primary)); }
.fast { animation: slide var(--motion-fast) ease-out infinite alternate; }
.medium { animation: slide var(--motion-medium) ease-out infinite alternate; }
.slow { animation: slide var(--motion-slow) ease-out infinite alternate; }
@keyframes slide { from { transform: translateX(0); } to { transform: translateX(8rem); } }
</style>
</head>
<body>
<main>
  <h1>APT design preview</h1>
  <p>Version ${version}. Generated from design/tokens/APT-TOKENS.json. Open this file directly. The historical standalone HTML files in apt-design-reference are not this preview.</p>
  <div class="row">
    <button class="outline" type="button" id="theme">Use light theme</button>
  </div>
  <h2>Color</h2>
  <div class="row">
    <div class="swatch"><i style="background:hsl(var(--background))"></i><span>background</span></div>
    <div class="swatch"><i style="background:hsl(var(--primary))"></i><span>primary</span></div>
    <div class="swatch"><i style="background:hsl(var(--accent))"></i><span>accent</span></div>
    <div class="swatch"><i style="background:hsl(var(--secondary))"></i><span>secondary</span></div>
    <div class="swatch"><i style="background:hsl(var(--success))"></i><span>success</span></div>
  </div>
  <h2>Buttons</h2>
  <p>Primary stays blue. Ghost and outline use the teal accent on hover. Keyboard focus is the blue ring.</p>
  <div class="row">
    <button class="primary" type="button">Primary</button>
    <button class="outline" type="button">Outline</button>
    <button class="ghost" type="button">Ghost</button>
  </div>
  <h2>Menu and dropdown</h2>
  <p>Highlighted options use the teal accent, including when focus moves onto the option.</p>
  <div class="menu" role="menu">
    <button class="option" type="button" role="menuitem">Overview</button>
    <button class="option" type="button" role="menuitem">Tokens</button>
    <button class="option" type="button" role="menuitem">Patterns</button>
  </div>
  <h2>Motion</h2>
  <p>fast ${tokens.animation.duration.fast.value}, normal ${tokens.animation.duration.normal.value}, slow ${tokens.animation.duration.slow.value}.</p>
  <div class="row"><div class="bar fast"></div><span>fast</span></div>
  <div class="row"><div class="bar medium"></div><span>normal</span></div>
  <div class="row"><div class="bar slow"></div><span>slow</span></div>
</main>
<script>
document.getElementById("theme").addEventListener("click", () => {
  const light = document.documentElement.classList.toggle("light");
  document.getElementById("theme").textContent = light ? "Use dark theme" : "Use light theme";
});
</script>
</body>
</html>
`;
}

function tokensTs() {
  const theme = (t) => Object.fromEntries(themeVariables(t));
  const data = { version, shared: Object.fromEntries(sharedVariables()), dark: theme("dark"), light: theme("light") };
  return `/*\n${HEADER("typed token values")}\n*/\nexport const aptDesignTokens = ${JSON.stringify(data, null, 2)} as const;\n\nexport type AptThemeName = "dark" | "light";\n`;
}

// Flat reference (references/design-tokens.json): only color values are generated; rules, aliases
// and non-color sections stay authored. Each flat key maps to a canonical dark token.
const FLAT_COLOR_MAP = {
  background: "background", surface: "card", surfaceElevated: "apt-surface-elevated", border: "border",
  borderSubtle: "apt-border-subtle", text: "foreground", textSecondary: "apt-text-secondary",
  textMuted: "muted-foreground", primary: "primary", primaryForeground: "primary-foreground",
  secondary: "secondary", secondaryForeground: "secondary-foreground", accent: "accent",
  accentForeground: "accent-foreground", danger: "destructive", dangerForeground: "destructive-foreground",
  warning: "warning", warningForeground: "warning-foreground", success: "success",
  successForeground: "success-foreground", link: "primary", focusRing: "ring", navActive: "primary",
  actionPrimary: "primary", selected: "primary", selectedSupport: "accent", glow: "apt-glow",
};
const flatHsl = (value) => `hsl(${channels(value).replace(" / ", ",").replace(/\s+/g, ",")})`;

function flatReference() {
  const file = path.join(root, "references", "design-tokens.json");
  const raw = readFileSync(file, "utf8");
  const reference = JSON.parse(raw);
  for (const [flat, canonical] of Object.entries(FLAT_COLOR_MAP)) {
    reference.tokens.color[flat] = flatHsl(tokens.color.dark[canonical].value);
  }
  for (const [index, token] of Object.entries(tokens.color.chart)) reference.tokens.color[`chart${index}`] = flatHsl(token.value);
  reference.tokens.color.overlay = flatHsl(tokens.color.dark.overlay.value);
  reference.tokens.colorLightStatus = Object.fromEntries(
    ["success", "success-foreground", "warning", "warning-foreground"].map((k) => [
      k.replace(/-(\w)/, (_m, c) => c.toUpperCase()),
      flatHsl(tokens.color.light[k].value),
    ]),
  );
  reference.designVersion = version;
  reference.source = "GENERATED color values from apt-principles-agents/design/tokens/APT-TOKENS.json by scripts/build-design.mjs (APT-019). Edit the canonical tokens, not this file's color sections.";
  return `${JSON.stringify(reference, null, 2)}\n`;
}

const outputs = {
  "design/generated/apt-tokens.css": tokensCss("light-first"),
  "design/generated/apt-tokens.dark-first.css": tokensCss("dark-first"),
  "design/generated/tailwind-preset.cjs": tailwindPreset(),
  "design/generated/apt-theme.css": tailwindV4Theme(),
  "design/generated/tokens.ts": tokensTs(),
  "design/generated/apt-preview.html": previewHtml(),
  "references/design-tokens.json": flatReference(),
};

const stale = [];
for (const [relative, content] of Object.entries(outputs)) {
  const file = path.join(root, relative);
  const current = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : null;
  if (current === content) continue;
  stale.push(relative);
  if (!checkOnly) {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
}

if (checkOnly && stale.length) {
  console.error(`Design artifacts are stale (run node scripts/build-design.mjs):\n${stale.map((f) => `- ${f}`).join("\n")}`);
  process.exit(1);
}
console.log(checkOnly ? `Design artifacts current (v${version}).` : `Design artifacts written (v${version}): ${stale.length ? stale.join(", ") : "no changes"}.`);
