#!/usr/bin/env node
// Generates the distributable APT design artifacts from the canonical tokens (APT-019).
//
//   design/tokens/APT-TOKENS.json  ->  design/dist/apt-tokens.css            (:root light, .dark dark)
//                                      design/dist/apt-tokens.dark-first.css (:root dark, .light light)
//                                      design/dist/tailwind-preset.cjs       (Tailwind v3 preset)
//                                      design/dist/apt-theme.css             (Tailwind v4 @theme inline)
//                                      design/dist/tokens.ts                 (typed values)
//                                      references/design-tokens.json         (color values only)
//
// Usage: node scripts/build-design.mjs [--check]
// --check writes nothing and exits 1 when any generated file is stale.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const tokensPath = path.join(root, "design", "tokens", "APT-TOKENS.json");
const version = readFileSync(path.join(root, "design", "VERSION"), "utf8").trim();
const tokens = JSON.parse(readFileSync(tokensPath, "utf8")).apt;

const HEADER = (what) =>
  `APT design tokens v${version} - ${what}.\n` +
  "GENERATED by apt-principles-agents/scripts/build-design.mjs from design/tokens/APT-TOKENS.json.\n" +
  "Do not edit: change the canonical tokens and re-run the generator, then sync with apt-assets.";

/** "hsl(220, 70%, 61%)" or "hsl(220, 20%, 4% / 0.82)" -> "220 70% 61%" / "220 20% 4% / 0.82" */
function channels(value) {
  const match = /^hsl\((.*)\)$/.exec(String(value).trim());
  if (!match) throw new Error(`Expected hsl() value, got ${value}`);
  return match[1].replace(/,/g, " ").replace(/\s+/g, " ").trim();
}

/** Ordered CSS custom properties for one theme. */
function themeVariables(theme) {
  const vars = [];
  for (const [name, token] of Object.entries(tokens.color[theme])) vars.push([name, channels(token.value)]);
  const charts = tokens.color[theme === "dark" ? "chart" : "chartLight"];
  for (const [index, token] of Object.entries(charts)) vars.push([`chart-${index}`, channels(token.value)]);
  for (let level = 1; level <= 4; level++) vars.push([`elevation-${level}`, tokens.shadow[`elevation-${level}-${theme}`].value]);
  vars.push(["elevation-glow-subtle", tokens.shadow["apt-glow-subtle"].value]);
  vars.push(["elevation-glow-strong", tokens.shadow["apt-glow-strong"].value]);
  vars.push(["elevation-hover-lift", tokens.shadow["apt-hover-lift"].value]);
  return vars;
}

function sharedVariables() {
  const duration = tokens.animation.duration;
  return [
    ["radius", tokens.borderRadius.lg.value],
    ["motion-fast", duration.fast.value],
    ["motion-medium", duration.normal.value],
    ["motion-slow", duration.slow.value],
  ];
}

const block = (selector, vars) => `${selector} {\n${vars.map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}`;

function tokensCss(layout) {
  const [rootTheme, classSelector, classTheme] = layout === "light-first" ? ["light", ".dark", "dark"] : ["dark", ".light", "light"];
  return [
    `/*\n${HEADER(`${layout} theme layout (:root ${rootTheme}, ${classSelector} ${classTheme})`)}\n*/`,
    block(":root", [...sharedVariables(), ...themeVariables(rootTheme)]),
    block(classSelector, themeVariables(classTheme)),
    "",
  ].join("\n\n");
}

/** Tailwind color map: semantic token -> hsl(var(--token)), grouping "<name>-foreground" pairs. */
function tailwindColors() {
  const names = Object.keys(tokens.color.dark);
  const colors = {};
  for (const name of names) {
    if (name.endsWith("-foreground") && names.includes(name.replace(/-foreground$/, ""))) continue;
    if (name.startsWith("sidebar-")) continue;
    const foreground = `${name}-foreground`;
    colors[name] = names.includes(foreground)
      ? { DEFAULT: `hsl(var(--${name}))`, foreground: `hsl(var(--${foreground}))` }
      : `hsl(var(--${name}))`;
  }
  colors.sidebar = { DEFAULT: "hsl(var(--sidebar-background))" };
  for (const name of names.filter((n) => n.startsWith("sidebar-") && n !== "sidebar-background")) {
    colors.sidebar[name.replace("sidebar-", "")] = `hsl(var(--${name}))`;
  }
  colors.chart = Object.fromEntries(Object.keys(tokens.color.chart).map((i) => [i, `hsl(var(--chart-${i}))`]));
  return colors;
}

function tailwindPreset() {
  const container = tokens.container.maxWidth;
  const preset = {
    darkMode: ["class"],
    theme: {
      extend: {
        colors: tailwindColors(),
        borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
        boxShadow: {
          "elevation-1": "var(--elevation-1)",
          "elevation-2": "var(--elevation-2)",
          "elevation-3": "var(--elevation-3)",
          "elevation-4": "var(--elevation-4)",
          "apt-glow-subtle": "var(--elevation-glow-subtle)",
          "apt-glow-strong": "var(--elevation-glow-strong)",
          "apt-hover-lift": "var(--elevation-hover-lift)",
        },
        transitionDuration: { fast: "var(--motion-fast)", medium: "var(--motion-medium)", slow: "var(--motion-slow)" },
        maxWidth: Object.fromEntries(Object.entries(container).map(([k, v]) => [k, v.value])),
      },
    },
  };
  return `/*\n${HEADER("Tailwind CSS v3 preset")}\nUsage: presets: [require("./.apt/design/dist/tailwind-preset.cjs")]\n*/\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
}

function tailwindV4Theme() {
  const lines = [];
  const flatten = (prefix, value) => {
    if (typeof value === "string") lines.push(`  --color-${prefix}: ${value};`);
    else for (const [k, v] of Object.entries(value)) flatten(k === "DEFAULT" ? prefix : `${prefix}-${k}`, v);
  };
  for (const [name, value] of Object.entries(tailwindColors())) flatten(name, value);
  for (let level = 1; level <= 4; level++) lines.push(`  --shadow-elevation-${level}: var(--elevation-${level});`);
  lines.push("  --radius-lg: var(--radius);", "  --radius-md: calc(var(--radius) - 2px);", "  --radius-sm: calc(var(--radius) - 4px);");
  return `/*\n${HEADER("Tailwind CSS v4 theme mapping")}\nImport after apt-tokens*.css: @import "./.apt/design/dist/apt-theme.css";\n*/\n@theme inline {\n${lines.join("\n")}\n}\n`;
}

function tokensTs() {
  const theme = (t) => Object.fromEntries(themeVariables(t));
  const data = { version, shared: Object.fromEntries(sharedVariables()), dark: theme("dark"), light: theme("light") };
  return `/*\n${HEADER("typed token values")}\n*/\nexport const aptDesignTokens = ${JSON.stringify(data, null, 2)} as const;\n\nexport type AptThemeName = "dark" | "light";\n`;
}

// Flat reference (references/design-tokens.json): only color values are generated; rules, aliases
// and non-color sections stay authored. Each flat key maps to a canonical dark token.
const FLAT_COLOR_MAP = {
  background: "background", surface: "card", surfaceElevated: "apt-surface-elevated", border: "border",
  borderSubtle: "apt-border-subtle", text: "foreground", textSecondary: "apt-text-secondary",
  textMuted: "muted-foreground", primary: "primary", primaryForeground: "primary-foreground",
  secondary: "secondary", secondaryForeground: "secondary-foreground", accent: "accent",
  accentForeground: "accent-foreground", danger: "destructive", dangerForeground: "destructive-foreground",
  warning: "warning", warningForeground: "warning-foreground", success: "success",
  successForeground: "success-foreground", link: "primary", focusRing: "ring", navActive: "primary",
  actionPrimary: "primary", selected: "primary", selectedSupport: "accent", glow: "apt-glow",
};
const flatHsl = (value) => `hsl(${channels(value).replace(" / ", ",").replace(/\s+/g, ",")})`;

function flatReference() {
  const file = path.join(root, "references", "design-tokens.json");
  const raw = readFileSync(file, "utf8");
  const reference = JSON.parse(raw);
  for (const [flat, canonical] of Object.entries(FLAT_COLOR_MAP)) {
    reference.tokens.color[flat] = flatHsl(tokens.color.dark[canonical].value);
  }
  for (const [index, token] of Object.entries(tokens.color.chart)) reference.tokens.color[`chart${index}`] = flatHsl(token.value);
  reference.tokens.color.overlay = flatHsl(tokens.color.dark.overlay.value);
  reference.tokens.colorLightStatus = Object.fromEntries(
    ["success", "success-foreground", "warning", "warning-foreground"].map((k) => [
      k.replace(/-(\w)/, (_m, c) => c.toUpperCase()),
      flatHsl(tokens.color.light[k].value),
    ]),
  );
  reference.designVersion = version;
  reference.source = "GENERATED color values from apt-principles-agents/design/tokens/APT-TOKENS.json by scripts/build-design.mjs (APT-019). Edit the canonical tokens, not this file's color sections.";
  return `${JSON.stringify(reference, null, 2)}\n`;
}

const outputs = {
  "design/dist/apt-tokens.css": tokensCss("light-first"),
  "design/dist/apt-tokens.dark-first.css": tokensCss("dark-first"),
  "design/dist/tailwind-preset.cjs": tailwindPreset(),
  "design/dist/apt-theme.css": tailwindV4Theme(),
  "design/dist/tokens.ts": tokensTs(),
  "references/design-tokens.json": flatReference(),
};

const stale = [];
for (const [relative, content] of Object.entries(outputs)) {
  const file = path.join(root, relative);
  const current = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : null;
  if (current === content) continue;
  stale.push(relative);
  if (!checkOnly) {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
}

if (checkOnly && stale.length) {
  console.error(`Design artifacts are stale (run node scripts/build-design.mjs):\n${stale.map((f) => `- ${f}`).join("\n")}`);
  process.exit(1);
}
console.log(checkOnly ? `Design artifacts current (v${version}).` : `Design artifacts written (v${version}): ${stale.length ? stale.join(", ") : "no changes"}.`);
